# **Pytorch Basics**


In [ ]:
import torch
import numpy as np

In [ ]:
# (https://towardsdatascience.com/understanding-pytorch-with-an-example-a-step-by-step-tutorial-81fc5f8c4e8e#ea0d)

## Specifying at the creation
t0 = torch.tensor([1,2])
t1 = torch.tensor([1,2], dtype=torch.float) # set to float
t2 =  torch.tensor([1,2], dtype=torch.float, requires_grad=True) # set as "trainable"
t3 = torch.tensor([1,2], dtype=torch.float, requires_grad=True, device="cuda") # send to gpu 
for i, t in enumerate([t0, t1, t2, t3]):
  print(f"Tensor No.{i}: {t}")
  print("="*50)

In [ ]:
## Object-oriented modifications

t0 = torch.tensor([1,2])
t1 = t0.float()
t2 =  t1.clone().requires_grad_() # set as "trainable"
t3 = t2.to("cuda") # send to gpu

for i, t in enumerate([t0, t1, t2, t3]):
  print(f"Tensor No.{i}: {t}")
  print("="*50)

Tensor No.0: tensor([1, 2])
Tensor No.1: tensor([1., 2.])
Tensor No.2: tensor([1., 2.], requires_grad=True)
Tensor No.3: tensor([1., 2.], device='cuda:0', grad_fn=<ToCopyBackward0>)


In [ ]:
# https://deeplearning.neuromatch.io/tutorials/W1D1_BasicsAndPytorch/student/W1D1_Tutorial1.html#section-2-1-creating-tensors

# tensor from a list
a = torch.tensor([0, 1, 2])
## Output: tensor([0, 1, 2])

#tensor from a tuple of tuples
b = ((1.0, 1.1), (1.2, 1.3))
b = torch.tensor(b)
## Output: tensor([[1.0000, 1.1000], [1.2000, 1.3000]])

# tensor from a numpy array
c = np.ones([2, 3])
c = torch.tensor(c)
## Output: tensor([[1., 1., 1.], [1., 1., 1.]], dtype=torch.float64)

print(f"Tensor a: {a}")
print(f"Tensor b: {b}")
print(f"Tensor c: {c}")

Tensor a: tensor([0, 1, 2])
Tensor b: tensor([[1.0000, 1.1000],
        [1.2000, 1.3000]])
Tensor c: tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [ ]:
# The numerical arguments we pass to these constructors
# determine the shape of the output tensor

x = torch.ones(5, 3)
y = torch.zeros(2)
z = torch.empty(1, 1, 5)
print(f"Tensor x: {x}")
print(f"Tensor y: {y}")
print(f"Tensor z: {z}")

Tensor x: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Tensor y: tensor([0., 0.])
Tensor z: tensor([[[6.8394e+10, 0.0000e+00, 3.3631e-44, 0.0000e+00,        nan]]])


In [ ]:
# There are also constructors for random numbers

# Uniform distribution
a = torch.rand(1, 3)

# Normal distribution
b = torch.randn(3, 4)

# There are also constructors that allow us to construct
# a tensor according to the above constructors, but with
# dimensions equal to another tensor.

c = torch.zeros_like(a)
d = torch.rand_like(c)

print(f"Tensor a: {a}")
print(f"Tensor b: {b}")
print(f"Tensor c: {c}")
print(f"Tensor d: {d}")

Tensor a: tensor([[0.2682, 0.5959, 0.2128]])
Tensor b: tensor([[-0.8738, -0.1772,  0.4323, -0.2663],
        [-0.7605, -1.0207,  0.4249, -0.7663],
        [-0.4242,  1.1462,  1.6569,  0.1874]])
Tensor c: tensor([[0., 0., 0.]])
Tensor d: tensor([[0.6727, 0.8597, 0.4815]])


### Tensor operations

In [ ]:
a = torch.ones(5, 3)
b = torch.rand(5, 3)
c = torch.empty(5, 3)
d = torch.empty(5, 3)

# this only works if c and d already exist
torch.add(a, b, out=c)

# Pointwise Multiplication of a and b
torch.multiply(a, b, out=d)

print(c)
print(d)

tensor([[1.3422, 1.3137, 1.4704],
        [1.2535, 1.2245, 1.6278],
        [1.6259, 1.2711, 1.1124],
        [1.2396, 1.1882, 1.0181],
        [1.5936, 1.0874, 1.7335]])
tensor([[0.3422, 0.3137, 0.4704],
        [0.2535, 0.2245, 0.6278],
        [0.6259, 0.2711, 0.1124],
        [0.2396, 0.1882, 0.0181],
        [0.5936, 0.0874, 0.7335]])


In [ ]:
x = torch.rand(3, 3)
print(x)
print("\n")
# sum() - note the axis is the axis you move across when summing
print(f"Sum of every element of x: {x.sum()}")
print(f"Sum of the columns of x: {x.sum(axis=0)}")
print(f"Sum of the rows of x: {x.sum(axis=1)}")
print("\n")

print(f"Mean value of all elements of x {x.mean()}")
print(f"Mean values of the columns of x {x.mean(axis=0)}")
print(f"Mean values of the rows of x {x.mean(axis=1)}")

tensor([[0.9711, 0.6206, 0.3660],
        [0.7614, 0.8319, 0.1086],
        [0.0110, 0.1012, 0.9091]])


Sum of every element of x: 4.680755615234375
Sum of the columns of x: tensor([1.7434, 1.5536, 1.3837])
Sum of the rows of x: tensor([1.9576, 1.7019, 1.0212])


Mean value of all elements of x 0.5200839638710022
Mean values of the columns of x tensor([0.5811, 0.5179, 0.4612])
Mean values of the rows of x tensor([0.6525, 0.5673, 0.3404])


In [ ]:
a1 = torch.tensor([[2, 4], [5, 7]])
a2 = torch.tensor([[1, 1], [2, 3]])
a3 = torch.tensor([[10, 10], [12, 1]])

a1 @ a2 + a3

tensor([[20, 24],
        [31, 27]])

In [ ]:
## https://www.geeksforgeeks.org/python-pytorch-stack-method/

a1 = torch.tensor([1, 2, 3, 4])
a2 = torch.tensor([5, 6, 7, 8])

a_stacked_0 = torch.stack((a1, a2), dim = 0) # ทับ
# Output: tensor([[1, 2, 3, 4],
#                 [5, 6, 7, 8]])

a_stacked_1 = torch.stack((a1, a2), dim = 1) # แปะข้างๆ
# Output: tensor([[1, 5],
#                 [2, 6],
#                 [3, 7],
#                 [4, 8]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])


In [ ]:
a1 = torch.tensor([1, 2, 3, 4])

print(a1.view(4,1))
# Output: tensor([[1],
#                 [2],
#                 [3],
#                 [4]])

print(a1.view(2,2))
# Output: tensor([[1, 2],
                # [3, 4]])

print(a1.view(-1, 2))
# Output: tensor([[1, 2],
#                 [3, 4]])

tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [ ]:
a2 = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])

print(a2.view(2,2,2))
# Output: tensor([[[1, 2],
#                  [3, 4]],

#                 [[5, 6],
#                  [7, 8]]])

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [ ]:
a3 = a2.view(1,8)
print(a3.size())
# Output: torch.Size([1, 8])

a3_t = torch.transpose(a3, 0, 1) # swap dim 0 and 1.
print(a3_t.size())
# Output: torch.Size([8, 1])

print("="*50)

a4 = a2.view(4,2,1)
print(a4.size())
# Output: torch.Size([4, 2, 1])

a4_t = torch.transpose(a4, 0, 1) # swap dim 0 and 1
print(a4_t.size())
# Output: torch.Size([2, 4, 1])

torch.Size([1, 8])
torch.Size([8, 1])
torch.Size([4, 2, 1])
torch.Size([2, 4, 1])


## Neural Networks


In [ ]:
# https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html

import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.flatten = nn.Flatten()
        # 28 * 28 is the image dimension
        self.fc1 = nn.Linear(28 * 28, 28)
        # 10 is the total number of classes
        self.fc2 = nn.Linear(28, 10)

    def forward(self, x):
      x = self.flatten(x)
      x = self.fc1(x)
      x = F.relu(x) # optionally apply some non-linearity here
      x = self.fc2(x)
      return x

In [ ]:
net = Net()
print(net)
print("="*50)

input = torch.randn(1, 28, 28) # ignore 1 for now
out = net(input)
print(f"Output shape: {out.shape}")

Net(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (fc1): Linear(in_features=784, out_features=28, bias=True)
  (fc2): Linear(in_features=28, out_features=1, bias=True)
)
Output shape: torch.Size([1, 1])


## Loss

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

## 1/3 incorrect
labels = torch.tensor([1, 1, 0], dtype=torch.float) # Dog, Dog, Cat
predictions = torch.tensor([1, 0, 0], dtype=torch.float, requires_grad=True) # Dog, Cat, Cat

loss_fn = nn.BCELoss(reduction="mean")
loss = loss_fn(predictions, labels)


loss # tensor(33.3333, grad_fn=<BinaryCrossEntropyBackward0>)

tensor(33.3333, grad_fn=<BinaryCrossEntropyBackward0>)

## Gradients

In [ ]:
a = torch.tensor([1.5], requires_grad=True)
b = torch.tensor([-1.5], requires_grad=True)
c = a + b
print(f'Gradient function = {c.grad_fn}')

Gradient function = <AddBackward0 object at 0x7fe7c89eb890>


In [ ]:
loss.backward()

## Datasets & Dataloaders

In [ ]:
from torch.utils.data import Dataset
# import pandas as pd

class AnimalDataset(Dataset):
    def __init__(self, filenames, labels):
        self.filenames = filenames
        self.labels = labels

    ## An alternative...
    # def __init__(self, dataframe):
    #     self.filenames = list(dataframe["filenames"].values)
    #     self.labels = list(dataframe["labels"].values)
        
    def __getitem__(self, index):
        return (self.filenames[index], self.labels[index])

    def __len__(self):
        return len(self.filenames)

train_data = AnimalDataset(train_filenames, train_labels)

In [ ]:
from torch.utils.data import DataLoader

train_loader = DataLoader(dataset=train_data, batch_size=16, shuffle=True)

In [ ]:
# https://pytorch.org/tutorials/beginner/basics/optimization_tutorial.html#optimizer

def train_loop(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    # Iterate over the dataloader
    for batch, (X, y) in enumerate(dataloader):
        # Compute prediction and loss
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # Report loss every 100 batch
        if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")


def test_loop(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0

    # Prevent Pytorch from updating the gradients at the testing steps!
    with torch.no_grad():
        for X, y in dataloader:
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")
    return test_loss

In [ ]:
from torch.optim.lr_scheduler import ReduceLROnPlateau
epochs = 50
learning_rate = 1e-3

loss_fn = nn.CrossEntropyLoss() # loss function for classification
optimizer = torch.optim.SGD(net.parameters(), lr=learning_rate) # Optimizer
scheduler = ReduceLROnPlateau(optimizer, "min")

for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train_loop(train_dataloader, net, loss_fn, optimizer)
    val_loss = test_loop(val_dataloader, net, loss_fn, optimizer)
    scheduler.step(val_loss)
print("Done!")